name: Update Doc

# on:
#   workflow_run:
#     workflows:
#       - "CLI Release"
#     types:
#       - completed
on:
  push:

jobs:
  update_doc:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write 
    steps:      
      - name: Check out code
        uses: actions/checkout@v3
        with:
          repository: L-Joli/devcycle-docs-fork
          # need to get/update access token
          token: ${{ secrets.PAT_TOKEN }}
          fetch-depth: 0

      - name: Set Git author
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
      
      - name: Get latest tag and set branch name
        run: |
          echo "LATEST_TAG=$(git describe --abbrev=0 --tags)" >> $GITHUB_ENV   
          echo "BRANCH_NAME=update-cli-version-to-$LATEST_TAG" >> $GITHUB_ENV   

      - name: Update CLI version in docs repo
        run: |
          git checkout -b "$BRANCH_NAME"
          sed -i 's/const DVC_CLI_VERSION = .*/const DVC_CLI_VERSION = '\''$LATEST_TAG'\'' \/\/ auto updated by dvc cli release workflow/' docusaurus.config.js
          git add docusaurus.config.js
          git commit -m "Update CLI version to $LATEST_TAG"

      - name: Push code to docs repo
        run:  |
          git push --set-upstream origin "$BRANCH_NAME"

      - name: Create PR
        env:
        # need to get/update access token
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: gh pr create --repo L-Joli/devcycle-docs-fork --base main --head "$BRANCH_NAME" --title "Update CLI version to $LATEST_TAG" --body "This PR was automatically created by the DevCycle CLI release workflow."