name: GitHub Release
description: Create a GitHub release and publish to NPM

inputs:
  github-token:
    required: true
    description: 'The GitHub token to use for authentication'

runs:
  using: 'composite'
  steps:
    - name: Create GitHub Release
      uses: DevCycleHQ/release-action/gh-release@main
      with:
        draft: false
        prerelease: false
        github-token: ${{ inputs.github-token }}

    # - name: Publish to NPM
    #   shell: bash
    #   env:
    #     NODE_AUTH_TOKEN: ${{ secrets.NPMJS_ACCESS_TOKEN }}
    #   run: npm publish --access public
