name: Update Doc

description: 'Update the CLI version in the docs repo'

inputs:
  latest_tag:
    required: true
    description: 'The latest tag from the workflow that uses this action'
  access_token:
    required: true
    description: 'The access token to use for authentication'

runs:
  using: 'composite'
  steps:
    - name: Check out code
      uses: actions/checkout@v3
      with:
        repository: L-Joli/devcycle-docs-fork
        # need to get/update access token
        token: ${{ inputs.access_token }}
        fetch-depth: 0
    
    - name: Set Git author
      shell: bash
      run: |
        git config user.name 'github-actions[bot]'
        git config user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Set branch name
      shell: bash
      id: get-branch-name
      run: echo "BRANCH_NAME=update-cli-version-to-${{ inputs.latest_tag }} >> $GITHUB_ENV

    - name: Update CLI version in docs repo
      shell: bash
      run: |
        git checkout -b "$BRANCH_NAME"
        sed -i 's/const DVC_CLI_VERSION = .*/const DVC_CLI_VERSION = '\''${{ inputs.latest_tag }}'\'' \/\/ auto updated by dvc cli release workflow/' docusaurus.config.js
        git add docusaurus.config.js
        git commit -m "Update CLI version to ${{ inputs.latest_tag }}"

    - name: Push code to docs repo
      shell: bash
      run: git push --set-upstream origin "$BRANCH_NAME"

    - name: Create PR
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.access_token }}
      run: gh pr create --repo L-Joli/devcycle-docs-fork --base main --head "$BRANCH_NAME" --title "Update CLI version to $LATEST_TAG" --body "This PR was automatically created by the DevCycle CLI release workflow."
