name: CLI Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Create GitHub Release
        uses: DevCycleHQ/release-action@main
        with:
          draft: true
          prerelease: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          
      # - name: Publish to NPM
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPMJS_ACCESS_TOKEN }}
      #   run: npm publish --access public  
