name: Tag New Version

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 12 * * 2'  # Runs every Tuesday at 12:00 PM (noon) ET

jobs:
  tag-new-version:
    runs-on: ubuntu-latest
    steps:      
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}

      - name: Set Git author
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
      
      - name: Install jq tool
        run: |
          sudo apt-get update
          sudo apt-get install jq

      - name: Get node version
        run: |
          echo "NVMRC=$(cat .nvmrc)" >> $GITHUB_ENV

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "$NVMRC"

      - name: Install dependencies
        run: yarn install
        
      - name: Build
        run: yarn build

      - name: Bump CLI version
        run: npm version patch --force

      - name: Get latest tag
        run: echo "LATEST_TAG=$(git describe --abbrev=0 --tags)" >> $GITHUB_ENV
          
      - name: Commit and push tag to main branch
        run: |
          echo "LATEST TAG: $LATEST_TAG"
          git add .
          git commit --amend -m "Release $LATEST_TAG"
          git tag -f $LATEST_TAG
          git push origin main --follow-tags